server:
  port: 8085
  
ribbon:
  ServerListRefreshInterval: 1000

endpoints:
  health:
    sensitive: false
  restart:
    enabled: true
  shutdown:
    enabled: true  

spring:
  application:
    name: SpringBootDocker
  datasource:
    driverClassName: org.postgresql.Driver
    platform: postgres
    url: jdbc:postgresql://localhost:5432/world-db
    username: world
    password: world123
    continue-on-error: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          lob: 
            non_contextual_creation: true
    hibernate: 
      ddl-auto: none    

